[2025-07-18T05:28:09.234+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T05:28:09.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_model_dag.check_drift_flag scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T05:28:09.312+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_model_dag.check_drift_flag scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T05:28:09.313+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-18T05:28:09.377+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): check_drift_flag> on 2025-07-17 00:00:00+00:00
[2025-07-18T05:28:09.384+0000] {standard_task_runner.py:63} INFO - Started process 54 to run task
[2025-07-18T05:28:09.390+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'retrain_model_dag', 'check_drift_flag', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/retrain_model_dag.py', '--cfg-path', '/tmp/tmptpihns_6']
[2025-07-18T05:28:09.392+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask check_drift_flag
[2025-07-18T05:28:09.556+0000] {task_command.py:426} INFO - Running <TaskInstance: retrain_model_dag.check_drift_flag scheduled__2025-07-17T00:00:00+00:00 [running]> on host e1044c091a34
[2025-07-18T05:28:09.801+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retrain_model_dag' AIRFLOW_CTX_TASK_ID='check_drift_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-17T00:00:00+00:00'
[2025-07-18T05:28:09.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T05:28:09.834+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-18T05:28:09.845+0000] {python.py:237} INFO - Done. Returned value was: retrain_model
[2025-07-18T05:28:09.847+0000] {branch.py:36} INFO - Branch into retrain_model
[2025-07-18T05:28:09.848+0000] {skipmixin.py:178} INFO - Following branch retrain_model
[2025-07-18T05:28:09.906+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_drift', -1)]
[2025-07-18T05:28:10.013+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T05:28:10.082+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=retrain_model_dag, task_id=check_drift_flag, execution_date=20250717T000000, start_date=20250718T052809, end_date=20250718T052810
[2025-07-18T05:28:10.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-18T05:28:10.222+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-18T05:28:10.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
